spring:
  application:
    name: eco-knock-be-central
  profiles:
    default: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
  threads:
    virtual:
      enabled: true

server:
  port: 18081

springdoc:
  api-docs:
    path: /v3/api-docs
  info:
    title: eco-knock-be-central API
    version: 0.0.1-SNAPSHOT

scalar:
  enabled: true
  path: /scalar

security:
  auth-policy:
    access-token-ttl: 6h
    refresh-token-ttl: 60d
    guest-session-ttl: 24h
    guest-login-rate-limit: 5
    guest-login-rate-limit-window: 1h
  admin:
    master-password: ${ADMIN_MASTER_PASSWORD}
    sso-member-id: 0
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  aes256:
    key: ${AES256_KEY}
  wallet:
    encryption-key: ${WALLET_ENCRYPTION_KEY}
  uri:
    allowed-front-end-origins:
      - http://localhost:*
      - https://localhost:*
      - https://eco-knock-fe.vercel.app
    allowed-admin-origins:
      - http://localhost:*
      - https://localhost:*
      - ${PROD_THIS_SERVER_URL}

embedded:
  grpc:
    host: ${EMBEDDED_SERVER_HOST}
    port: ${EMBEDDED_SERVER_GRPC_PORT}
    timeout: 3s

sso:
  base-url: https://auth.econovation.kr
  client-id: ${SSO_CLIENT_ID}

whozin:
  base-url: https://be.whozin.econovation.kr
  token: ${WHOZIN_TOKEN}

blockchain:
  ethereum-sepolia:
    rpc-url: ${SEPOLIA_RPC_URL}
    krt-token-address: ${SEPOLIA_KRT_TOKEN_ADDRESS}

ai-server:
  base-url: ${AI_SERVER_HOST}
  timeout: 30s

management:
  server:
    port: 18082
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      access: unrestricted
