spring:
  datasource:
    url: jdbc:postgresql://${DEV_POSTGRES_HOST:localhost}:${DEV_POSTGRES_PORT:5432}/ecoknock
    username: ${DEV_POSTGRES_USERNAME:postgres}
    password: ${DEV_POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.format_sql: true
    defer-datasource-initialization: false
    hibernate.ddl-auto: validate
  data:
    redis:
      host: ${DEV_REDIS_HOST:localhost}
      port: ${DEV_REDIS_PORT:6379}

security:
  uri:
    admin-origin: http://localhost:18081

grafana:
  url: http://${DEV_GRAFANA_HOST:localhost}:${DEV_GRAFANA_PORT:3000}
