spring:
  datasource:
    url: jdbc:postgresql://${PROD_POSTGRES_HOST}:${PROD_POSTGRES_PORT}/ecoknock
    username: ${PROD_POSTGRES_USERNAME}
    password: ${PROD_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.format_sql: true
    defer-datasource-initialization: false
    hibernate.ddl-auto: validate
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}

grafana:
  url: ${PROD_GRAFANA_HOST}
