global:
  scrape_interval: 15s

scrape_configs:
  - job_name: eco-knock-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "app:18082" ]
        labels:
          environment: prod

  - job_name: eco-knock-embedded
    metrics_path: /metrics
    static_configs:
      - targets: [ "__EMBEDDED_SERVER_HOST__:19996" ]
        labels:
          environment: prod
          service: embedded
