global:
  scrape_interval: 15s

scrape_configs:
  - job_name: eco-knock-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "app:18082" ]
        labels:
          environment: prod
