CREATE TABLE ai_chat_history
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE,
    updated_at         TIMESTAMP WITH TIME ZONE,
    member_id          BIGINT                                  NOT NULL,
    question           TEXT                                    NOT NULL,
    answer             TEXT                                    NOT NULL,
    file_url           VARCHAR(2048),
    file_name          VARCHAR(255),
    file_content_type  VARCHAR(100),
    file_size          BIGINT,
    raw_response       JSONB                                   NOT NULL,
    CONSTRAINT pk_ai_chat_history PRIMARY KEY (id),
    CONSTRAINT fk_ai_chat_history_member
        FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE INDEX idx_ai_chat_history_member_created_at
    ON ai_chat_history (member_id, created_at DESC);
