CREATE TABLE member_wallet
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE,
    updated_at            TIMESTAMP WITH TIME ZONE,
    member_id             BIGINT                                  NOT NULL,
    wallet_address        VARCHAR(42)                             NOT NULL,
    encrypted_private_key TEXT,
    wallet_type           VARCHAR(32)                             NOT NULL,
    is_active             BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_member_wallet PRIMARY KEY (id),
    CONSTRAINT uk_member_wallet_address UNIQUE (wallet_address),
    CONSTRAINT ck_member_wallet_type CHECK (wallet_type IN ('MANAGED', 'EXTERNAL')),
    CONSTRAINT ck_member_wallet_private_key CHECK (
        (wallet_type = 'MANAGED' AND encrypted_private_key IS NOT NULL)
        OR (wallet_type = 'EXTERNAL' AND encrypted_private_key IS NULL)
    )
);

ALTER TABLE member_wallet
    ADD CONSTRAINT fk_member_wallet_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE;

CREATE INDEX idx_member_wallet_member_id
    ON member_wallet (member_id);

CREATE UNIQUE INDEX uk_member_wallet_managed_per_member
    ON member_wallet (member_id)
    WHERE wallet_type = 'MANAGED';

CREATE UNIQUE INDEX uk_member_wallet_active_per_member
    ON member_wallet (member_id)
    WHERE is_active = TRUE;
