CREATE TABLE reward_distribution
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE,
    updated_at          TIMESTAMP WITH TIME ZONE,
    settlement_date     DATE                                    NOT NULL,
    batch_id            VARCHAR(66)                             NOT NULL,
    transaction_hash    VARCHAR(66),
    total_reward_amount BIGINT                                  NOT NULL,
    recipient_count     INTEGER                                 NOT NULL,
    status              VARCHAR(16)                             NOT NULL,
    CONSTRAINT pk_reward_distribution PRIMARY KEY (id),
    CONSTRAINT uk_reward_distribution_date UNIQUE (settlement_date),
    CONSTRAINT uk_reward_distribution_batch_id UNIQUE (batch_id),
    CONSTRAINT uk_reward_distribution_tx_hash UNIQUE (transaction_hash),
    CONSTRAINT ck_reward_distribution_total CHECK (total_reward_amount > 0),
    CONSTRAINT ck_reward_distribution_recipients CHECK (recipient_count > 0),
    CONSTRAINT ck_reward_distribution_status CHECK (
        status IN ('PENDING', 'SUBMITTING', 'SUBMITTED', 'CONFIRMED', 'FAILED')
    )
);

CREATE INDEX idx_reward_distribution_status
    ON reward_distribution (status);
