CREATE TABLE overview_layout
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    member_id  BIGINT                                  NOT NULL,
    grid_size  INTEGER                                 NOT NULL,
    CONSTRAINT pk_overview_layout PRIMARY KEY (id),
    CONSTRAINT uk_overview_layout_member_id UNIQUE (member_id),
    CONSTRAINT fk_overview_layout_member FOREIGN KEY (member_id) REFERENCES member (id)
);

INSERT INTO overview_layout (created_at, updated_at, member_id, grid_size)
SELECT now(), now(), id, 3
FROM member
ON CONFLICT (member_id) DO NOTHING;
