CREATE TABLE reward_history
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE,
    updated_at        TIMESTAMP WITH TIME ZONE,
    member_id         BIGINT                                 NOT NULL,
    distribution_id   BIGINT                                 NOT NULL,
    reward_type       VARCHAR(16)                            NOT NULL,
    reward_amount     BIGINT                                 NOT NULL,
    stay_hours        INTEGER,
    wallet_address    VARCHAR(66)                            NOT NULL,
    CONSTRAINT pk_reward_history PRIMARY KEY (id),
    CONSTRAINT fk_reward_history_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_reward_history_distribution FOREIGN KEY (distribution_id) REFERENCES reward_distribution (id),
    CONSTRAINT ck_reward_history_type CHECK (reward_type IN ('ATTENDANCE', 'STAY_DURATION')),
    CONSTRAINT ck_reward_history_amount CHECK (reward_amount > 0),
    CONSTRAINT ck_reward_history_stay_hours CHECK (
        (reward_type = 'ATTENDANCE' AND stay_hours IS NULL)
        OR (reward_type = 'STAY_DURATION' AND stay_hours IS NOT NULL AND stay_hours > 0)
    ),
    CONSTRAINT uk_reward_history_distribution_member_type
        UNIQUE (distribution_id, member_id, reward_type)
);

CREATE INDEX idx_reward_history_member_id
    ON reward_history (member_id);

CREATE INDEX idx_reward_history_distribution_id
    ON reward_history (distribution_id);

CREATE INDEX idx_reward_history_reward_type
    ON reward_history (reward_type);
