CREATE TABLE air_quality
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE,
    updated_at               TIMESTAMP WITH TIME ZONE,
    sensor_measured_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    air_purifier_measured_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    pm25                     INTEGER                                 NOT NULL,
    humidity                 DOUBLE PRECISION                        NOT NULL,
    temperature              DOUBLE PRECISION                        NOT NULL,
    estimated_eco2ppm        DOUBLE PRECISION                        NOT NULL,
    estimated_bvocppm        DOUBLE PRECISION                        NOT NULL,
    accuracy                 INTEGER                                 NOT NULL,
    raw_sensor               JSONB,
    raw_air_purifier         JSONB,
    CONSTRAINT pk_airquality PRIMARY KEY (id)
);

CREATE TABLE member
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    role       VARCHAR(255)                            NOT NULL,
    name       TEXT                                    NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    provider   VARCHAR(255)                            NOT NULL,
    cohort     INTEGER                                 NOT NULL,
    CONSTRAINT pk_member PRIMARY KEY (id)
);


create index idx_air_quality_sensor_measured_at
    on air_quality (sensor_measured_at desc);
