CREATE TABLE air_quality_history_setting
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    member_id  BIGINT                                  NOT NULL,
    resolution VARCHAR(16)                             NOT NULL,
    CONSTRAINT pk_air_quality_history_setting PRIMARY KEY (id),
    CONSTRAINT uk_air_quality_history_setting_member UNIQUE (member_id),
    CONSTRAINT ck_air_quality_history_setting_resolution
        CHECK (resolution IN ('ONE_MINUTE', 'FIVE_MINUTES', 'FIFTEEN_MINUTES', 'ONE_HOUR', 'FOUR_HOURS', 'ONE_DAY'))
);

ALTER TABLE air_quality_history_setting
    ADD CONSTRAINT fk_air_quality_history_setting_member
        FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE;

INSERT INTO air_quality_history_setting (member_id, resolution)
SELECT id, 'FIFTEEN_MINUTES'
FROM member;
