CREATE TABLE light_report
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE,
    lux         DOUBLE PRECISION                        NOT NULL,
    measured_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    raw_als     INTEGER                                 NOT NULL,
    raw_white   INTEGER                                 NOT NULL,
    CONSTRAINT pk_lightreport PRIMARY KEY (id)
);

