CREATE TABLE default_overview_shortcut
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    icon_url   VARCHAR(2048)                           NOT NULL,
    target_url VARCHAR(2048)                           NOT NULL,
    sort_order INTEGER                                 NOT NULL,
    name       VARCHAR(2048)                           NOT NULL,
    CONSTRAINT pk_defaultoverviewshortcut PRIMARY KEY (id)
);

CREATE TABLE overview_shortcut
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    member_id  BIGINT                                  NOT NULL,
    icon_url   VARCHAR(2048)                           NOT NULL,
    target_url VARCHAR(2048)                           NOT NULL,
    sort_order INTEGER                                 NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_overviewshortcut PRIMARY KEY (id)
);

ALTER TABLE overview_shortcut
    ADD CONSTRAINT fk_overviewshortcut_member
        FOREIGN KEY (member_id) REFERENCES member (id);

CREATE INDEX idx_default_overview_shortcut_sort_order
    ON default_overview_shortcut (sort_order);

CREATE INDEX idx_overview_shortcut_member_id_sort_order
    ON overview_shortcut (member_id, sort_order);
