create index idx_light_report_measured_at
    on light_report (measured_at desc);

create table control_action_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    acted_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    decision   VARCHAR(32)                             NOT NULL,
    reason     TEXT                                    NOT NULL,
    CONSTRAINT pk_control_action_log PRIMARY KEY (id)
);

create index idx_control_action_log_acted_at
    on control_action_log (acted_at desc);
