package jnu.econovation.ecoknockbecentral.auth.exception

import jnu.econovation.ecoknockbecentral.common.exception.client.ClientException
import jnu.econovation.ecoknockbecentral.common.exception.constants.ErrorCode

class GuestLoginRateLimitExceededException : ClientException(ErrorCode.GUEST_LOGIN_RATE_LIMIT_EXCEEDED)
